# Generated by Django 5.0 on 2024-02-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminstration',
            fields=[
                ('AdminId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('AdminName', models.CharField(max_length=50)),
                ('AdminPhoneNo', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('MentorID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('MentorName', models.CharField(max_length=50)),
                ('MentorPhoneNumber', models.CharField(max_length=12)),
                ('MentorDepartment', models.CharField(max_length=20)),
                ('MentorRoomNo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=50)),
                ('StudentCourse', models.CharField(max_length=20)),
                ('StudentClass', models.CharField(max_length=10)),
                ('StudentPhoneNumber', models.CharField(max_length=12)),
                ('MentorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApply.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='AbsentReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=10)),
                ('AdminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApply.adminstration')),
                ('MentorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApply.mentor')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApply.student')),
            ],
        ),
    ]
