# Generated by Django 5.0 on 2024-02-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminstration',
            name='Password',
            field=models.TextField(default='123456789'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='Password',
            field=models.TextField(default='123456789'),
        ),
        migrations.AddField(
            model_name='student',
            name='Password',
            field=models.TextField(default='123456789'),
        ),
    ]
