# Generated by Django 5.0 on 2024-02-22 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApply', '0003_alter_absentreason_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absentreason',
            name='AdminId',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='StudentApply.adminstration'),
        ),
    ]
