# Generated by Django 5.0 on 2024-02-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApply', '0005_remove_absentreason_adminid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StudentCourse',
            field=models.CharField(max_length=50),
        ),
    ]
